# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea06cbf5c6eb16f3f886c6cb20425ae22ce78641262b3f1d51ed8867589107a2520fb9f2668a6f73e55c947002603a758ed81fdf41f2902b7448a8acaee765a2

test:
  secret_key_base: ceff0d59fbcc488cd4e6937c980180b079c46c945f6070be7058d4b6145e3efec9eaec61665d89ff9c9979378ed26a8b47e1ae758b306b2095453a574a3dc83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 25b4c4c76bf7990b2b17924c97f0b15662064ded8d285dc03ee82e1b84deee7362b78250d090e406f78306df41e0b94b1f2120eefe6ec78e8be0ff3e6648c0df
